import { initializeApp } from 'firebase/app';
import { getAuth, signInAnonymously } from 'firebase/auth';
import { getFirestore, collection, getDocs } from 'firebase/firestore';
const cfg = { apiKey:'AIzaSyDiIS-TDH6MgXaLvG9T2VRioFDomQ_zQ9E', authDomain:'inspection-time-c4fd3.firebaseapp.com', projectId:'inspection-time-c4fd3' };
const app = initializeApp(cfg);
const cred = await signInAnonymously(getAuth(app));
const tok = await cred.user.getIdToken();
const db = getFirestore(app);
const NS = 'product-inspection-v1';
const J = t => t ? new Date(Number(t)).toLocaleString('ja-JP') : '-';
console.log('auth ok');
const reqs = await getDocs(collection(db,'artifacts',NS,'public','data','contact_requests'));
const comp = []; const kinds = {};
reqs.forEach(s => { const d = s.data(); kinds[d.kind||'?']=(kinds[d.kind||'?']||0)+1; if (d.kind==='complete') comp.push({id:s.id,...d}); });
comp.sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));
console.log('連絡の内訳:', JSON.stringify(kinds));
console.log('=== kind=complete:', comp.length, '件 ===');
for (const c of comp) console.log([J(c.createdAt), c.orderNo||'(指図なし)', c.model||'', `→${c.to}`, `from=${c.from}`, `status=${c.status}`, `needAck=${c.needAck}`, c.answer?`返信:${c.answer.choice}/${c.answer.by||'?'}/${J(c.answer.at)}`:'返信なし'].join(' | '));
const base = `https://firestore.googleapis.com/v1/projects/${cfg.projectId}/databases/(default)/documents/artifacts/${NS}/public/data/lots`;
let pageToken='', notified={}, total=0;
do {
  const url = `${base}?pageSize=300&mask.fieldPaths=completeNotified&mask.fieldPaths=orderNo${pageToken?`&pageToken=${encodeURIComponent(pageToken)}`:''}`;
  const r = await fetch(url, { headers: { Authorization: `Bearer ${tok}` } });
  const j = await r.json();
  if (j.error) { console.log('REST ERR', JSON.stringify(j.error).slice(0,300)); break; }
  (j.documents||[]).forEach(d => { total++; const f=d.fields||{}; const cn=f.completeNotified?.mapValue?.fields;
    if (cn) notified[d.name.split('/').pop()] = { reqId: cn.reqId?.stringValue, at: Number(cn.at?.integerValue||0), by: cn.by?.stringValue, group: cn.group?.stringValue, orderNo: f.orderNo?.stringValue }; });
  pageToken = j.nextPageToken || '';
  console.log('  ...lots読み込み', total);
} while (pageToken);
console.log('lots総数:', total, '/ completeNotified印あり:', Object.keys(notified).length);
const ids = new Set(comp.map(c=>c.id));
const pairedReq = new Set(Object.values(notified).map(v=>v.reqId).filter(Boolean));
console.log('--- 連絡あり/lot印なし:', comp.filter(c=>!pairedReq.has(c.id)).map(c=>`${c.orderNo}@${J(c.createdAt)}`).join(', ') || 'なし');
Object.values(notified).forEach(v => { if (v.reqId && !ids.has(v.reqId)) console.log('⚠ lot印あり/連絡なし:', v.orderNo, J(v.at), v.by, v.group); });
